import * as FiIcon from "react-icons/fi";

export const IconMap = {
  FiActivity: <FiIcon.FiActivity />,
  FiAirplay: <FiIcon.FiAirplay />,
  FiAlertCircle: <FiIcon.FiAlertCircle />,
  FiAlertOctagon: <FiIcon.FiAlertOctagon />,
  FiAlertTriangle: <FiIcon.FiAlertTriangle />,
  FiAlignCenter: <FiIcon.FiAlignCenter />,
  FiAlignJustify: <FiIcon.FiAlignJustify />,
  FiAlignLeft: <FiIcon.FiAlignLeft />,
  FiAlignRight: <FiIcon.FiAlignRight />,
  FiAnchor: <FiIcon.FiAnchor />,
  FiAperture: <FiIcon.FiAperture />,
  FiArchive: <FiIcon.FiArchive />,
  FiArrowDownCircle: <FiIcon.FiArrowDownCircle />,
  FiArrowDownLeft: <FiIcon.FiArrowDownLeft />,
  FiArrowDownRight: <FiIcon.FiArrowDownRight />,
  FiArrowDown: <FiIcon.FiArrowDown />,
  FiArrowLeftCircle: <FiIcon.FiArrowLeftCircle />,
  FiArrowLeft: <FiIcon.FiArrowLeft />,
  FiArrowRightCircle: <FiIcon.FiArrowRightCircle />,
  FiArrowRight: <FiIcon.FiArrowRight />,
  FiArrowUpCircle: <FiIcon.FiArrowUpCircle />,
  FiArrowUpLeft: <FiIcon.FiArrowUpLeft />,
  FiArrowUpRight: <FiIcon.FiArrowUpRight />,
  FiArrowUp: <FiIcon.FiArrowUp />,
  FiAtSign: <FiIcon.FiAtSign />,
  FiAward: <FiIcon.FiAward />,
  FiBarChart2: <FiIcon.FiBarChart2 />,
  FiBarChart: <FiIcon.FiBarChart />,
  FiBatteryCharging: <FiIcon.FiBatteryCharging />,
  FiBattery: <FiIcon.FiBattery />,
  FiBellOff: <FiIcon.FiBellOff />,
  FiBell: <FiIcon.FiBell />,
  FiBluetooth: <FiIcon.FiBluetooth />,
  FiBold: <FiIcon.FiBold />,
  FiBookOpen: <FiIcon.FiBookOpen />,
  FiBook: <FiIcon.FiBook />,
  FiBookmark: <FiIcon.FiBookmark />,
  FiBox: <FiIcon.FiBox />,
  FiBriefcase: <FiIcon.FiBriefcase />,
  FiCalendar: <FiIcon.FiCalendar />,
  FiCameraOff: <FiIcon.FiCameraOff />,
  FiCamera: <FiIcon.FiCamera />,
  FiCast: <FiIcon.FiCast />,
  FiCheckCircle: <FiIcon.FiCheckCircle />,
  FiCheckSquare: <FiIcon.FiCheckSquare />,
  FiCheck: <FiIcon.FiCheck />,
  FiChevronDown: <FiIcon.FiChevronDown />,
  FiChevronLeft: <FiIcon.FiChevronLeft />,
  FiChevronRight: <FiIcon.FiChevronRight />,
  FiChevronUp: <FiIcon.FiChevronUp />,
  FiChevronsDown: <FiIcon.FiChevronsDown />,
  FiChevronsLeft: <FiIcon.FiChevronsLeft />,
  FiChevronsRight: <FiIcon.FiChevronsRight />,
  FiChevronsUp: <FiIcon.FiChevronsUp />,
  FiChrome: <FiIcon.FiChrome />,
  FiCircle: <FiIcon.FiCircle />,
  FiClipboard: <FiIcon.FiClipboard />,
  FiClock: <FiIcon.FiClock />,
  FiCloudDrizzle: <FiIcon.FiCloudDrizzle />,
  FiCloudLightning: <FiIcon.FiCloudLightning />,
  FiCloudOff: <FiIcon.FiCloudOff />,
  FiCloudRain: <FiIcon.FiCloudRain />,
  FiCloudSnow: <FiIcon.FiCloudSnow />,
  FiCloud: <FiIcon.FiCloud />,
  FiCode: <FiIcon.FiCode />,
  FiCodepen: <FiIcon.FiCodepen />,
  FiCodesandbox: <FiIcon.FiCodesandbox />,
  FiCoffee: <FiIcon.FiCoffee />,
  FiColumns: <FiIcon.FiColumns />,
  FiCommand: <FiIcon.FiCommand />,
  FiCompass: <FiIcon.FiCompass />,
  FiCopy: <FiIcon.FiCopy />,
  FiCornerDownLeft: <FiIcon.FiCornerDownLeft />,
  FiCornerDownRight: <FiIcon.FiCornerDownRight />,
  FiCornerLeftDown: <FiIcon.FiCornerLeftDown />,
  FiCornerLeftUp: <FiIcon.FiCornerLeftUp />,
  FiCornerRightDown: <FiIcon.FiCornerRightDown />,
  FiCornerRightUp: <FiIcon.FiCornerRightUp />,
  FiCornerUpLeft: <FiIcon.FiCornerUpLeft />,
  FiCornerUpRight: <FiIcon.FiCornerUpRight />,
  FiCpu: <FiIcon.FiCpu />,
  FiCreditCard: <FiIcon.FiCreditCard />,
  FiCrop: <FiIcon.FiCrop />,
  FiCrosshair: <FiIcon.FiCrosshair />,
  FiDatabase: <FiIcon.FiDatabase />,
  FiDelete: <FiIcon.FiDelete />,
  FiDisc: <FiIcon.FiDisc />,
  FiDivideCircle: <FiIcon.FiDivideCircle />,
  FiDivideSquare: <FiIcon.FiDivideSquare />,
  FiDivide: <FiIcon.FiDivide />,
  FiDollarSign: <FiIcon.FiDollarSign />,
  FiDownloadCloud: <FiIcon.FiDownloadCloud />,
  FiDownload: <FiIcon.FiDownload />,
  FiDribbble: <FiIcon.FiDribbble />,
  FiDroplet: <FiIcon.FiDroplet />,
  FiEdit2: <FiIcon.FiEdit2 />,
  FiEdit3: <FiIcon.FiEdit3 />,
  FiEdit: <FiIcon.FiEdit />,
  FiExternalLink: <FiIcon.FiExternalLink />,
  FiEyeOff: <FiIcon.FiEyeOff />,
  FiEye: <FiIcon.FiEye />,
  FiFacebook: <FiIcon.FiFacebook />,
  FiFastForward: <FiIcon.FiFastForward />,
  FiFeather: <FiIcon.FiFeather />,
  FiFigma: <FiIcon.FiFigma />,
  FiFileMinus: <FiIcon.FiFileMinus />,
  FiFilePlus: <FiIcon.FiFilePlus />,
  FiFileText: <FiIcon.FiFileText />,
  FiFile: <FiIcon.FiFile />,
  FiFilm: <FiIcon.FiFilm />,
  FiFilter: <FiIcon.FiFilter />,
  FiFlag: <FiIcon.FiFlag />,
  FiFolderMinus: <FiIcon.FiFolderMinus />,
  FiFolderPlus: <FiIcon.FiFolderPlus />,
  FiFolder: <FiIcon.FiFolder />,
  FiFramer: <FiIcon.FiFramer />,
  FiFrown: <FiIcon.FiFrown />,
  FiGift: <FiIcon.FiGift />,
  FiGitBranch: <FiIcon.FiGitBranch />,
  FiGitCommit: <FiIcon.FiGitCommit />,
  FiGitMerge: <FiIcon.FiGitMerge />,
  FiGitPullRequest: <FiIcon.FiGitPullRequest />,
  FiGithub: <FiIcon.FiGithub />,
  FiGitlab: <FiIcon.FiGitlab />,
  FiGlobe: <FiIcon.FiGlobe />,
  FiGrid: <FiIcon.FiGrid />,
  FiHardDrive: <FiIcon.FiHardDrive />,
  FiHash: <FiIcon.FiHash />,
  FiHeadphones: <FiIcon.FiHeadphones />,
  FiHeart: <FiIcon.FiHeart />,
  FiHelpCircle: <FiIcon.FiHelpCircle />,
  FiHexagon: <FiIcon.FiHexagon />,
  FiHome: <FiIcon.FiHome />,
  FiImage: <FiIcon.FiImage />,
  FiInbox: <FiIcon.FiInbox />,
  FiInfo: <FiIcon.FiInfo />,
  FiInstagram: <FiIcon.FiInstagram />,
  FiItalic: <FiIcon.FiItalic />,
  FiKey: <FiIcon.FiKey />,
  FiLayers: <FiIcon.FiLayers />,
  FiLayout: <FiIcon.FiLayout />,
  FiLifeBuoy: <FiIcon.FiLifeBuoy />,
  FiLink2: <FiIcon.FiLink2 />,
  FiLink: <FiIcon.FiLink />,
  FiLinkedin: <FiIcon.FiLinkedin />,
  FiList: <FiIcon.FiList />,
  FiLoader: <FiIcon.FiLoader />,
  FiLock: <FiIcon.FiLock />,
  FiLogIn: <FiIcon.FiLogIn />,
  FiLogOut: <FiIcon.FiLogOut />,
  FiMail: <FiIcon.FiMail />,
  FiMapPin: <FiIcon.FiMapPin />,
  FiMap: <FiIcon.FiMap />,
  FiMaximize2: <FiIcon.FiMaximize2 />,
  FiMaximize: <FiIcon.FiMaximize />,
  FiMeh: <FiIcon.FiMeh />,
  FiMenu: <FiIcon.FiMenu />,
  FiMessageCircle: <FiIcon.FiMessageCircle />,
  FiMessageSquare: <FiIcon.FiMessageSquare />,
  FiMicOff: <FiIcon.FiMicOff />,
  FiMic: <FiIcon.FiMic />,
  FiMinimize2: <FiIcon.FiMinimize2 />,
  FiMinimize: <FiIcon.FiMinimize />,
  FiMinusCircle: <FiIcon.FiMinusCircle />,
  FiMinusSquare: <FiIcon.FiMinusSquare />,
  FiMinus: <FiIcon.FiMinus />,
  FiMonitor: <FiIcon.FiMonitor />,
  FiMoon: <FiIcon.FiMoon />,
  FiMoreHorizontal: <FiIcon.FiMoreHorizontal />,
  FiMoreVertical: <FiIcon.FiMoreVertical />,
  FiMousePointer: <FiIcon.FiMousePointer />,
  FiMove: <FiIcon.FiMove />,
  FiMusic: <FiIcon.FiMusic />,
  FiNavigation2: <FiIcon.FiNavigation2 />,
  FiNavigation: <FiIcon.FiNavigation />,
  FiOctagon: <FiIcon.FiOctagon />,
  FiPackage: <FiIcon.FiPackage />,
  FiPaperclip: <FiIcon.FiPaperclip />,
  FiPauseCircle: <FiIcon.FiPauseCircle />,
  FiPause: <FiIcon.FiPause />,
  FiPenTool: <FiIcon.FiPenTool />,
  FiPercent: <FiIcon.FiPercent />,
  FiPhoneCall: <FiIcon.FiPhoneCall />,
  FiPhoneForwarded: <FiIcon.FiPhoneForwarded />,
  FiPhoneIncoming: <FiIcon.FiPhoneIncoming />,
  FiPhoneMissed: <FiIcon.FiPhoneMissed />,
  FiPhoneOff: <FiIcon.FiPhoneOff />,
  FiPhoneOutgoing: <FiIcon.FiPhoneOutgoing />,
  FiPhone: <FiIcon.FiPhone />,
  FiPieChart: <FiIcon.FiPieChart />,
  FiPlayCircle: <FiIcon.FiPlayCircle />,
  FiPlay: <FiIcon.FiPlay />,
  FiPlusCircle: <FiIcon.FiPlusCircle />,
  FiPlusSquare: <FiIcon.FiPlusSquare />,
  FiPlus: <FiIcon.FiPlus />,
  FiPocket: <FiIcon.FiPocket />,
  FiPower: <FiIcon.FiPower />,
  FiPrinter: <FiIcon.FiPrinter />,
  FiRadio: <FiIcon.FiRadio />,
  FiRefreshCcw: <FiIcon.FiRefreshCcw />,
  FiRefreshCw: <FiIcon.FiRefreshCw />,
  FiRepeat: <FiIcon.FiRepeat />,
  FiRewind: <FiIcon.FiRewind />,
  FiRotateCcw: <FiIcon.FiRotateCcw />,
  FiRotateCw: <FiIcon.FiRotateCw />,
  FiRss: <FiIcon.FiRss />,
  FiSave: <FiIcon.FiSave />,
  FiScissors: <FiIcon.FiScissors />,
  FiSearch: <FiIcon.FiSearch />,
  FiSend: <FiIcon.FiSend />,
  FiServer: <FiIcon.FiServer />,
  FiSettings: <FiIcon.FiSettings />,
  FiShare2: <FiIcon.FiShare2 />,
  FiShare: <FiIcon.FiShare />,
  FiShieldOff: <FiIcon.FiShieldOff />,
  FiShield: <FiIcon.FiShield />,
  FiShoppingBag: <FiIcon.FiShoppingBag />,
  FiShoppingCart: <FiIcon.FiShoppingCart />,
  FiShuffle: <FiIcon.FiShuffle />,
  FiSidebar: <FiIcon.FiSidebar />,
  FiSkipBack: <FiIcon.FiSkipBack />,
  FiSkipForward: <FiIcon.FiSkipForward />,
  FiSlack: <FiIcon.FiSlack />,
  FiSlash: <FiIcon.FiSlash />,
  FiSliders: <FiIcon.FiSliders />,
  FiSmartphone: <FiIcon.FiSmartphone />,
  FiSmile: <FiIcon.FiSmile />,
  FiSpeaker: <FiIcon.FiSpeaker />,
  FiSquare: <FiIcon.FiSquare />,
  FiStar: <FiIcon.FiStar />,
  FiStopCircle: <FiIcon.FiStopCircle />,
  FiSun: <FiIcon.FiSun />,
  FiSunrise: <FiIcon.FiSunrise />,
  FiSunset: <FiIcon.FiSunset />,
  FiTable: <FiIcon.FiTable />,
  FiTablet: <FiIcon.FiTablet />,
  FiTag: <FiIcon.FiTag />,
  FiTarget: <FiIcon.FiTarget />,
  FiTerminal: <FiIcon.FiTerminal />,
  FiThermometer: <FiIcon.FiThermometer />,
  FiThumbsDown: <FiIcon.FiThumbsDown />,
  FiThumbsUp: <FiIcon.FiThumbsUp />,
  FiToggleLeft: <FiIcon.FiToggleLeft />,
  FiToggleRight: <FiIcon.FiToggleRight />,
  FiTool: <FiIcon.FiTool />,
  FiTrash2: <FiIcon.FiTrash2 />,
  FiTrash: <FiIcon.FiTrash />,
  FiTrello: <FiIcon.FiTrello />,
  FiTrendingDown: <FiIcon.FiTrendingDown />,
  FiTrendingUp: <FiIcon.FiTrendingUp />,
  FiTriangle: <FiIcon.FiTriangle />,
  FiTruck: <FiIcon.FiTruck />,
  FiTv: <FiIcon.FiTv />,
  FiTwitch: <FiIcon.FiTwitch />,
  FiTwitter: <FiIcon.FiTwitter />,
  FiType: <FiIcon.FiType />,
  FiUmbrella: <FiIcon.FiUmbrella />,
  FiUnderline: <FiIcon.FiUnderline />,
  FiUnlock: <FiIcon.FiUnlock />,
  FiUploadCloud: <FiIcon.FiUploadCloud />,
  FiUpload: <FiIcon.FiUpload />,
  FiUserCheck: <FiIcon.FiUserCheck />,
  FiUserMinus: <FiIcon.FiUserMinus />,
  FiUserPlus: <FiIcon.FiUserPlus />,
  FiUserX: <FiIcon.FiUserX />,
  FiUser: <FiIcon.FiUser />,
  FiUsers: <FiIcon.FiUsers />,
  FiVideoOff: <FiIcon.FiVideoOff />,
  FiVideo: <FiIcon.FiVideo />,
  FiVoicemail: <FiIcon.FiVoicemail />,
  FiVolume1: <FiIcon.FiVolume1 />,
  FiVolume2: <FiIcon.FiVolume2 />,
  FiVolumeX: <FiIcon.FiVolumeX />,
  FiVolume: <FiIcon.FiVolume />,
  FiWatch: <FiIcon.FiWatch />,
  FiWifiOff: <FiIcon.FiWifiOff />,
  FiWifi: <FiIcon.FiWifi />,
  FiWind: <FiIcon.FiWind />,
  FiXCircle: <FiIcon.FiXCircle />,
  FiXOctagon: <FiIcon.FiXOctagon />,
  FiXSquare: <FiIcon.FiXSquare />,
  FiX: <FiIcon.FiX />,
  FiYoutube: <FiIcon.FiYoutube />,
  FiZapOff: <FiIcon.FiZapOff />,
  FiZap: <FiIcon.FiZap />,
  FiZoomIn: <FiIcon.FiZoomIn />,
  FiZoomOut: <FiIcon.FiZoomOut />,
};
export const stringIconMap = [
  "FiActivity",
  "FiAirplay",
  "FiAlertCircle",
  "FiAlertOctagon",
  "FiAlertTriangle",
  "FiAlignCenter",
  "FiAlignJustify",
  "FiAlignLeft",
  "FiAlignRight",
  "FiAnchor",
  "FiAperture",
  "FiArchive",
  "FiArrowDownCircle",
  "FiArrowDownLeft",
  "FiArrowDownRight",
  "FiArrowDown",
  "FiArrowLeftCircle",
  "FiArrowLeft",
  "FiArrowRightCircle",
  "FiArrowRight",
  "FiArrowUpCircle",
  "FiArrowUpLeft",
  "FiArrowUpRight",
  "FiArrowUp",
  "FiAtSign",
  "FiAward",
  "FiBarChart2",
  "FiBarChart",
  "FiBatteryCharging",
  "FiBattery",
  "FiBellOff",
  "FiBell",
  "FiBluetooth",
  "FiBold",
  "FiBookOpen",
  "FiBook",
  "FiBookmark",
  "FiBox",
  "FiBriefcase",
  "FiCalendar",
  "FiCameraOff",
  "FiCamera",
  "FiCast",
  "FiCheckCircle",
  "FiCheckSquare",
  "FiCheck",
  "FiChevronDown",
  "FiChevronLeft",
  "FiChevronRight",
  "FiChevronUp",
  "FiChevronsDown",
  "FiChevronsLeft",
  "FiChevronsRight",
  "FiChevronsUp",
  "FiChrome",
  "FiCircle",
  "FiClipboard",
  "FiClock",
  "FiCloudDrizzle",
  "FiCloudLightning",
  "FiCloudOff",
  "FiCloudRain",
  "FiCloudSnow",
  "FiCloud",
  "FiCode",
  "FiCodepen",
  "FiCodesandbox",
  "FiCoffee",
  "FiColumns",
  "FiCommand",
  "FiCompass",
  "FiCopy",
  "FiCornerDownLeft",
  "FiCornerDownRight",
  "FiCornerLeftDown",
  "FiCornerLeftUp",
  "FiCornerRightDown",
  "FiCornerRightUp",
  "FiCornerUpLeft",
  "FiCornerUpRight",
  "FiCpu",
  "FiCreditCard",
  "FiCrop",
  "FiCrosshair",
  "FiDatabase",
  "FiDelete",
  "FiDisc",
  "FiDivideCircle",
  "FiDivideSquare",
  "FiDivide",
  "FiDollarSign",
  "FiDownloadCloud",
  "FiDownload",
  "FiDribbble",
  "FiDroplet",
  "FiEdit2",
  "FiEdit3",
  "FiEdit",
  "FiExternalLink",
  "FiEyeOff",
  "FiEye",
  "FiFacebook",
  "FiFastForward",
  "FiFeather",
  "FiFigma",
  "FiFileMinus",
  "FiFilePlus",
  "FiFileText",
  "FiFile",
  "FiFilm",
  "FiFilter",
  "FiFlag",
  "FiFolderMinus",
  "FiFolderPlus",
  "FiFolder",
  "FiFramer",
  "FiFrown",
  "FiGift",
  "FiGitBranch",
  "FiGitCommit",
  "FiGitMerge",
  "FiGitPullRequest",
  "FiGithub",
  "FiGitlab",
  "FiGlobe",
  "FiGrid",
  "FiHardDrive",
  "FiHash",
  "FiHeadphones",
  "FiHeart",
  "FiHelpCircle",
  "FiHexagon",
  "FiHome",
  "FiImage",
  "FiInbox",
  "FiInfo",
  "FiInstagram",
  "FiItalic",
  "FiKey",
  "FiLayers",
  "FiLayout",
  "FiLifeBuoy",
  "FiLink2",
  "FiLink",
  "FiLinkedin",
  "FiList",
  "FiLoader",
  "FiLock",
  "FiLogIn",
  "FiLogOut",
  "FiMail",
  "FiMapPin",
  "FiMap",
  "FiMaximize2",
  "FiMaximize",
  "FiMeh",
  "FiMenu",
  "FiMessageCircle",
  "FiMessageSquare",
  "FiMicOff",
  "FiMic",
  "FiMinimize2",
  "FiMinimize",
  "FiMinusCircle",
  "FiMinusSquare",
  "FiMinus",
  "FiMonitor",
  "FiMoon",
  "FiMoreHorizontal",
  "FiMoreVertical",
  "FiMousePointer",
  "FiMove",
  "FiMusic",
  "FiNavigation2",
  "FiNavigation",
  "FiOctagon",
  "FiPackage",
  "FiPaperclip",
  "FiPauseCircle",
  "FiPause",
  "FiPenTool",
  "FiPercent",
  "FiPhoneCall",
  "FiPhoneForwarded",
  "FiPhoneIncoming",
  "FiPhoneMissed",
  "FiPhoneOff",
  "FiPhoneOutgoing",
  "FiPhone",
  "FiPieChart",
  "FiPlayCircle",
  "FiPlay",
  "FiPlusCircle",
  "FiPlusSquare",
  "FiPlus",
  "FiPocket",
  "FiPower",
  "FiPrinter",
  "FiRadio",
  "FiRefreshCcw",
  "FiRefreshCw",
  "FiRepeat",
  "FiRewind",
  "FiRotateCcw",
  "FiRotateCw",
  "FiRss",
  "FiSave",
  "FiScissors",
  "FiSearch",
  "FiSend",
  "FiServer",
  "FiSettings",
  "FiShare2",
  "FiShare",
  "FiShieldOff",
  "FiShield",
  "FiShoppingBag",
  "FiShoppingCart",
  "FiShuffle",
  "FiSidebar",
  "FiSkipBack",
  "FiSkipForward",
  "FiSlack",
  "FiSlash",
  "FiSliders",
  "FiSmartphone",
  "FiSmile",
  "FiSpeaker",
  "FiSquare",
  "FiStar",
  "FiStopCircle",
  "FiSun",
  "FiSunrise",
  "FiSunset",
  "FiTable",
  "FiTablet",
  "FiTag",
  "FiTarget",
  "FiTerminal",
  "FiThermometer",
  "FiThumbsDown",
  "FiThumbsUp",
  "FiToggleLeft",
  "FiToggleRight",
  "FiTool",
  "FiTrash2",
  "FiTrash",
  "FiTrello",
  "FiTrendingDown",
  "FiTrendingUp",
  "FiTriangle",
  "FiTruck",
  "FiTv",
  "FiTwitch",
  "FiTwitter",
  "FiType",
  "FiUmbrella",
  "FiUnderline",
  "FiUnlock",
  "FiUploadCloud",
  "FiUpload",
  "FiUserCheck",
  "FiUserMinus",
  "FiUserPlus",
  "FiUserX",
  "FiUser",
  "FiUsers",
  "FiVideoOff",
  "FiVideo",
  "FiVoicemail",
  "FiVolume1",
  "FiVolume2",
  "FiVolumeX",
  "FiVolume",
  "FiWatch",
  "FiWifiOff",
  "FiWifi",
  "FiWind",
  "FiXCircle",
  "FiXOctagon",
  "FiXSquare",
  "FiX",
  "FiYoutube",
  "FiZapOff",
  "FiZap",
  "FiZoomIn",
  "FiZoomOut",
];
